#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

# Image source
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/Armbian.img.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/Armbian.img.xz"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
