#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="armbian"

# Image source
DOWNLOAD_URL_CHECKSUM="https://github.com/liyiecho/armbian-msm8916/releases/latest/download/Armbian.img.sha256"
DOWNLOAD_URL_IMAGE="https://github.com/liyiecho/armbian-msm8916/releases/latest/download/Armbian.img.xz"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

export MODULES="base,pkgupgrade,udev_fix,armbian(armbian_net,mainsailos,klipper,node,is_req_preinstall,moonraker,mainsail,crowsnest,ratos(linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,disable-services(hotspot),dfu-util))"
